server:
  port: 9994
spring:
  jpa:
    hibernate:
      ddl-auto: update

    debug: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/bookingservice
    username: root
    password: sumit
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: BOOKING-SERVICE
    config: 
    import: optional:configserver:http://localhost:9997

feign:
    client:
    default:
     loggerLevel: FULL
    connectTimeout: 2000
    readTimeout: 3000

#resilience4j:
#    circuitbreaker:
#      instances:
#       fallbackGetAllUsers: # This is a method for dummy if user does not get a rating info
#       registerHealthIndicator: true
#       eventConsumerBufferSize: 10
#       failureRateThreshold: 50
#       minimumNumberOfCalls: 5
#      automaticTransitionFromOpenToHalfOpenEnabled: true
#      waitDurationInOpenState: 6s
#      permittedNumberOfCallsInHalfOpenState: 3
#      slidingWindowSize: 10
#      slidingWindowType: COUNT_BASED

#eureka:
#  client:
#    fetch-registry: true
#instance:
#    prefer-ip-address: true
#    register-with-eureka: true
#    service-url:
#      defaultzone:  http://localhost:8761/eureka/
