server:
  port: 9998

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:9991
          predicates:
            - Path=/v1/users/**,/v1/addresses/**,/v1/payment-methods/**,/v1/preferences/**
          filters:
            - AuthenticationFilter
            - AddRequestHeader=Gateway-Secret, testing

        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
          - Path=/v1/payments/**
          filters:
            - AuthenticationFilter
            - AddRequestHeader=Gateway-Secret, testing

        - id: BOOKING-SERVICE
          uri: lb://BOOKING-SERVICE
          predicates:
          - Path=/v1/bookings/**
          filters:
            - AuthenticationFilter
            - AddRequestHeader=Gateway-Secret, testing

        - id: MOVIE-SERVICE
          uri: lb://MOVIE-SERVICE
          predicates:
          - Path=/v1/genres/**,/v1/movies/**,/v1/screens/**,/v1/showtimes/**,/v1/theatres/*
          filters:
            - AuthenticationFilter
            - AddRequestHeader=Gateway-Secret, testing

        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
          - Path=/v1/notifications/**
          filters:
            - AuthenticationFilter
            - AddRequestHeader=Gateway-Secret, testing
   
  config:
    import: optional:configserver:http://localhost:9997
    fail-fast: false
    retry:
       maxAttempts: 20

logging:
    level:
      '[org.springframework.cloud.gateway]': TRACE

jwt:
    secret: testing
    validity: 20
    authDisabled: false

