server:
  port: 9998

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v1/users/**,/v1/addresses/**,/v1/payment-methods/**,/v1/preferences/**

        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
          - Path=/v1/payments/**

        - id: BOOKING-SERVICE
          uri: lb://BOOKING-SERVICE
          predicates:
          - Path=/v1/bookings/**

        - id: MOVIE-SERVICE
          uri: lb://MOVIE-SERVICE
          predicates:
          - Path=/v1/genres/**,/v1/movies/**,/v1/screens/**,/v1/showtimes/**,/v1/theatres/*

        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
          - Path=/v1/notifications/**
  config:
    import: optional:configserver:http://localhost:9997