server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost


spring:
  application:
    name: ServiceRegistry
  cloud:
    compatibility-verifier:
      enabled: false